"""Add profile_image to User model

Revision ID: 1b526f223142
Revises: 
Create Date: 2023-12-13 19:45:35.226985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b526f223142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('assessment_user_client', sa.Float(), nullable=False),
    sa.Column('comment_user_client', sa.Float(), nullable=False),
    sa.Column('assessment_user_provider', sa.Float(), nullable=False),
    sa.Column('comment_user_provier', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('canceled', 'evaluate', 'aproved'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('relationship_user_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_job'], ['job.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_relationship_user_job', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_create', sa.Date(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('attention_time', sa.Date(), nullable=False),
    sa.Column('id_assessment', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'in_progress', 'completed'), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_assessment'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['id_relationship_user_job'], ['relationship_user_job.id'], use_alter=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_relationship_user_job', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('attention_day', sa.Date(), nullable=False),
    sa.Column('attention_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_relationship_user_job'], ['relationship_user_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_detail')
    op.drop_table('service')
    op.drop_table('relationship_user_job')
    op.drop_table('user')
    op.drop_table('job')
    op.drop_table('assessment')
    # ### end Alembic commands ###
