"""empty message

Revision ID: 90de7032cbc8
Revises: f5fe038fc82a
Create Date: 2023-12-08 18:51:09.228407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90de7032cbc8'
down_revision = 'f5fe038fc82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'service', ['id_service'], ['id'], use_alter=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'relationship_user_job', ['id_relationship_user_job'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
