"""empty message

Revision ID: 3e69d6ac1d83
Revises: a2dda90597fc
Create Date: 2023-12-06 23:50:52.443759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e69d6ac1d83'
down_revision = 'a2dda90597fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_relation_user_job', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('attention_day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_relation_user_job'], ['relation_user_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_detail')
    # ### end Alembic commands ###
