"""empty message

Revision ID: 96dcc6b645e6
Revises: 3e69d6ac1d83
Create Date: 2023-12-06 23:53:31.344896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dcc6b645e6'
down_revision = '3e69d6ac1d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_detail', schema=None) as batch_op:
        batch_op.alter_column('attention_day',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_detail', schema=None) as batch_op:
        batch_op.alter_column('attention_day',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
