"""empty message

Revision ID: a2dda90597fc
Revises: f70f284ae0b5
Create Date: 2023-12-06 23:03:58.557078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dda90597fc'
down_revision = 'f70f284ae0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_user_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_job'], ['job.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_user_job')
    # ### end Alembic commands ###
